### ISSUE TITLE
improve efficiency

### ISSUE THREAD

**Issue by petar-dambovaliev** [sanpii/libpq.rs#11]
Hi,

There are places where allocations are happening, where they are not necessary.
For example, https://github.com/sanpii/libpq.rs/blob/main/src/connection/_copy.rs#L81 .
For this reason, we use the `libpq-sys` package and not the safe api.
The way we implemented it is to have a data structure with the pointer and call `PQfreemem` in the drop implementation.
Is this something you are interested in doing here?

**Comment by sanpii** [comment]
The next version will be a major version, it’s the best time to break the API.

It seems a good idea to reduce unnecessary allocation.

**Comment by iuridiniz** [comment]
Yes, I'm guilty about these changes (#10) , I did this because [CString::from_raw](https://doc.rust-lang.org/std/ffi/struct.CString.html#method.from_raw) was unsafe since memory was allocated by C. 

I was worry about memory getting allocated twice (one in rust, one in C)

If you guys give some specs, I can do a struct to store this. I already done this

This is a draft:
```
struct PGBuffer {
    ptr: *const u8,
    len: usize,
}

impl std::ops::Deref for PGBuffer {
    type Target = [u8];

    fn deref(&self) -> &[u8] {
        unsafe { std::slice::from_raw_parts(self.ptr, self.len) }
    }
}

impl Drop for PGBuffer {
    fn drop(&mut self) {
        unsafe {
            pq_sys::PQfreemem(self.ptr as *mut std::ffi::c_void);
        };
    }
}

impl PGBuffer {
    fn from_raw(ptr: *const u8, len: usize) -> PGBuffer {
        PGBuffer { ptr: ptr, len: len }
    }
}
```

**Comment by iuridiniz** [comment]
the `copy_data` will become (using my draft):

```rust
   pub fn copy_data(&self, r#async: bool) -> std::result::Result<PGBuffer, String> {
        let mut ptr = std::ptr::null_mut();

        let success = unsafe { pq_sys::PQgetCopyData(self.into(), &mut ptr, r#async as i32) };

        match success {
            -2 => Err(self
                .error_message()
                .unwrap_or_else(|| "Unknow error".to_string())),
            -1 => Err("COPY is done".to_string()),
            0 => Err("COPY still in progress".to_string()),
            nbytes => Ok(PGBuffer::from_raw(ptr as *const u8, nbytes as usize)),
        }
    }
 ```

**Comment by iuridiniz** [comment]
We can also improve this with implementation of a Deref to `&str` and/or `From<&'_ str>` (in order to get string slices), feel free guys.

**Comment by iuridiniz** [comment]
I'm implemented the draft in #12

**Comment by petar-dambovaliev** [comment]
> I'm implemented the draft in #12

The data structure should be more portable.

`struct PGBuffer(*mut std::ffi::c_void, usize);`

Also, can you add `SAFETY` comment blocks?

drop, for example
```
       //SAFETY: we take `self` as an exclusive reference
        // so we know it's safe to cast a mutable pointer
        // and drop only gets called when there are no more
        // references to the object
```

**Comment by petar-dambovaliev** [comment]
> the `copy_data` will become (using my draft):
> 
> ```rust
>    pub fn copy_data(&self, r#async: bool) -> std::result::Result<PGBuffer, String> {
>         let mut ptr = std::ptr::null_mut();
> 
>         let success = unsafe { pq_sys::PQgetCopyData(self.into(), &mut ptr, r#async as i32) };
> 
>         match success {
>             -2 => Err(self
>                 .error_message()
>                 .unwrap_or_else(|| "Unknow error".to_string())),
>             -1 => Err("COPY is done".to_string()),
>             0 => Err("COPY still in progress".to_string()),
>             nbytes => Ok(PGBuffer::from_raw(ptr as *const u8, nbytes as usize)),
>         }
>     }
> ```

There is also a problem with this function.
It is not following the postgres libpq documentation.

https://www.postgresql.org/docs/current/libpq-copy.html#LIBPQ-PQGETCOPYDATA
`After PQgetCopyData returns -1, call PQgetResult to obtain the final result status of the COPY command.`

And when calling `PQgetResult` we should also consult the documentation.
https://www.postgresql.org/docs/current/libpq-async.html#LIBPQ-PQGETRESULT
`PQgetResult must be called repeatedly until it returns a null pointer, indicating that the command is done. `

**Comment by iuridiniz** [comment]
Yeah, I'm not the maintainer of this project, but I've reach this project after looking to a lib to make a prototype of logical replication client and the return of 0 had relevant to me. So in order to make the prototype I made:

```rust
           Err(s) => {
                if s != "COPY still in progress" {
                    println!("Err: {}", s);
                } else {
                    std::thread::sleep(std::time::Duration::from_millis(100));
                    conn.consume_input().unwrap();
                }
            }
``` 

Not efficient, but it was Ok for a prototype. 
Please fill another bug just for this issue. If @sanpii agree I could see if I can work on it too.

**Comment by sanpii** [comment]
Is this issue can be close now?
