### ISSUE TITLE
Possible bug with memory allocation/deallocation for string escaping.

### ISSUE THREAD

**Issue by janis-ab** [sanpii/libpq.rs#37]
Hello everyone,

I've been reading libpq.rs source code and there is this thing with memory allocation, that does not seem to be correct and potencially could cause segfaults.

I might be wrong, maybe i have not taken everything into consideration, this is why i would like to discuss it.

So in file [src/escape.rs:36](https://github.com/sanpii/libpq.rs/blob/main/src/escape.rs#L36):
```rust
pub(crate) fn string_conn(conn: &crate::Connection, from: &str) -> crate::errors::Result<PqString> {
// ..
    let cstring = crate::ffi::new_cstring(2 * from.len() + 1);
    let raw = cstring.into_raw();
// ..
    unsafe {
        pq_sys::PQescapeStringConn(conn.into(), raw, c_from.as_ptr(), from.len(), &mut error);
// ..
    }
    Ok(PqString::from_raw(raw))
}
```
As per my understanding function `PQescapeStringConn` does not take ownership over `raw` pointer allocation in any way, because in documentation for [PQescapeStringConn](https://www.postgresql.org/docs/16/libpq-exec.html#LIBPQ-PQESCAPESTRINGCONN) it is stated that:
> Unlike PQescapeLiteral, the caller is responsible for providing an appropriately sized buffer.

As per my understanding `PQescapeStringConn` allows caller to manage memory buffer, thus allocated memory should be freed by the same allocator that allocated it; although it is not clearly stated in docs that function does not allocate anything internally.

So now we look into Rust documentation for [cstring.into_raw()](https://doc.rust-lang.org/std/ffi/struct.CString.html#method.into_raw). Documentation clearly states that:
> The pointer which this function returns **must be** returned to Rust and  reconstituted using CString::from_raw to be properly deallocated. Specifically, one should not use the standard C free() function to deallocate this string.

Now we look at returned struct PqString at [src/connection/buffer.rs:145](https://github.com/sanpii/libpq.rs/blob/main/src/connection/buffer.rs#L145):
```rust
pub struct PqString {
    ptr: *const libc::c_char,
}
```

It basically just takes ownership of pointer (which is fine by me). [src/connection/buffer.rs:185](https://github.com/sanpii/libpq.rs/blob/main/src/connection/buffer.rs#L185):
```rust
impl PqString {
    pub(crate) fn from_raw(ptr: *const libc::c_char) -> PqString {
        debug_assert!(!ptr.is_null(), "ptr must be not null");
        PqString { ptr }
    }
```

But then comes the kicker at [src/connection/buffer.rs:180](https://github.com/sanpii/libpq.rs/blob/main/src/connection/buffer.rs#L180):
```rust
impl Drop for PqString {
    fn drop(&mut self) {
        // SAFETY: This is safe because:
        // * This is the recommended way to free memory allocated by libpq.
        // ..
        unsafe {
            pq_sys::PQfreemem(self.ptr as *mut std::ffi::c_void);
        };
//..
```
I believe this is wrong, because of the following reasons:

The comment within Drop trait is a  bit ambiguous in phrase "allocated by libpq" - i believe in this context libpq refers to C library not the Rust  bindings, although names are kind of the same, thus a bit of ambiguity.

The documentation for [PQfreemem](https://www.postgresql.org/docs/16/libpq-misc.html#LIBPQ-PQFREEMEM) states that:
> Frees memory allocated by libpq, particularly PQescapeByteaConn, PQescapeBytea, PQunescapeBytea ..

If we look at definition for [PQescapeByteaConn](https://www.postgresql.org/docs/16/libpq-exec.html#LIBPQ-PQESCAPEBYTEACONN):
```c
unsigned char *PQescapeByteaConn(PGconn *conn,
                                 const unsigned char *from,
                                 size_t from_length,
                                 size_t *to_length);
```
We clearly see that it returns pointer to memory that is allocated, and in this case allocated by libpq (in a C library context). Documentation further states that:
> PQescapeByteaConn returns an escaped version of the from parameter binary string in memory allocated with malloc(). This memory **should be freed using PQfreemem()** when the result is no longer needed.

But if we look at libpq.rs function [escape::string_conn](https://github.com/sanpii/libpq.rs/blob/main/src/escape.rs#L36), then we clearly see that memory is not allocated by libpq(C library), but Rusts provided allocator (whatever that is within given process).

What's seems even worse is that some functions really do allocate PqString through libpq (C library) and should use PQfreemem, i.e.: `src/escape.rs:23`:
```rust
pub fn identifier(conn: &crate::Connection, str: &str) -> crate::errors::Result<PqString> {
    let c_str = crate::ffi::to_cstr(str);
    unsafe {
        let raw = pq_sys::PQescapeIdentifier(conn.into(), c_str.as_ptr(), str.len());
// ..
```
Relevant Postgresql documentation [PQescapeIdentifier](https://www.postgresql.org/docs/16/libpq-exec.html#LIBPQ-PQESCAPEBYTEACONN) states:
> PQescapeIdentifier returns a version of the str parameter escaped as an SQL identifier in memory allocated with malloc(). This memory must be freed using PQfreemem() when the result is no longer needed.

Yeah, we might get "lucky", because Rusts allocator uses the same underlying allocator that libpq (C lib) uses, but what gives the guarantee that this is true for all configurations?

I mean, libpq could decide to use different, custom allocator, maybe add some extra information. When testing library with valgrind or what not, another allocator could be used for statistics and analysis. In Rust you can implement/register your own [allocator](https://doc.rust-lang.org/std/alloc/trait.GlobalAlloc.html).

So, yeah, as per my understanding, this is a bug.

What are your comments on this? Have i missed something? Are there some mechanics that pass Rusts allocator to libpq (C library) so that it is guaranteed that the same allocator is used everywhere? Or is it just a luck that this bug was not spotted?

**Comment by sanpii** [comment]
Thank for your work! You right, I try with the jemallocator and I got this error:

```
free(): invalid pointer
```

**Comment by janis-ab** [comment]
Thank you for your work as well! It's nice to have a library onto which to build and improve upon, rather than doing all from ground up.

This one seems won't be easy to fix though.

**Comment by sanpii** [comment]
> This one seems won't be easy to fix though.

I don’t think so, `escape_string` should just returns a `String`.
