### ISSUE TITLE
Suggestion for Clarifying `Result` Types with Renaming

### ISSUE THREAD

**Issue by yjshen** [sanpii/libpq.rs#42]
Hi there!

Firstly, a huge thanks for `libpq.rs` – it's been super helpful in my Rust + PostgreSQL adventures. 😊

I noticed that we have two Result types in the project: `crate::Result` and `crate::errors::Result`. Both are widely used across the API, which is super intuitive but can get a bit tricky to distinguish from each other. To avoid any mix-ups and make the code even more approachable, what do you think about renaming `crate::Result` to something more distinct like `PQResult`? It could help distinguish them at a glance, especially for folks jumping into the project.

Just a thought! Your input would be greatly appreciated, and I’m all ears for alternative suggestions.

Thanks again for making our Rust journey smoother and more enjoyable!

**Comment by sanpii** [comment]
Hello,

I’m totally agree with you, but I don’t find a good name. Why not `PQResult`.

A bad name is probably better than a confusing one :slightly_smiling_face:

**Comment by yjshen** [comment]
Thanks a lot for the prompt response! I will create a PR for this.
