### ISSUE TITLE
PQconndefaults should return an array

### ISSUE THREAD

**Issue by pfumagalli** [sanpii/libpq.rs#45]
The `PQconndefaults` function actually seems to be returning an _array_ of `PQconninfoOption` structures.

As far as I can see, here, the code only considers the _first_ element in the array, ignoring all others

https://github.com/sanpii/libpq.rs/blob/2cc3094cdb5bf40e4ef17eeaaf10a3c59ca701fd/src/connection/info.rs#L105

As far as I can understand, it should return something similar to `PQconninfoPars` like here

https://github.com/sanpii/libpq.rs/blob/2cc3094cdb5bf40e4ef17eeaaf10a3c59ca701fd/src/connection/info.rs#L28

See here: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PQCONNDEFAULTS

**Comment by sanpii** [comment]
You right, thank you.

I depreciated the `new` function in favor of `defaults` who returns an array.
