### ISSUE TITLE
fails to compile on aws Graviton

### ISSUE THREAD

**Issue by petar-dambovaliev** [sanpii/libpq.rs#8]
```
error[E0308]: mismatched types
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libpq-1.3.3/src/result/mod.rs:272:21
    |
272 |             header: option.header as i8,
    |                     ^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`

error[E0308]: mismatched types
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libpq-1.3.3/src/result/mod.rs:273:20
    |
273 |             align: option.align as i8,
    |                    ^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`

error[E0308]: mismatched types
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libpq-1.3.3/src/result/mod.rs:274:23
    |
274 |             standard: option.standard as i8,
    |                       ^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
```

**Comment by sanpii** [comment]
Let me know if this PR fixes your problem: https://github.com/sanpii/libpq.rs/pull/9

**Comment by petar-dambovaliev** [comment]
> Let me know if this PR fixes your problem: #9

Thanks, i will try it.
As far as a permanent fix, maybe we should add conditional compilation based on the architecture?
What do you think?

**Comment by sanpii** [comment]
> As far as a permanent fix, maybe we should add conditional compilation based on the architecture?

This is what the `libc` crate does.

**Comment by petar-dambovaliev** [comment]
> Let me know if this PR fixes your problem: #9

I can't import your library from github.

```libpq = {git = "https://github.com/sanpii/libpq.rs", branch = "arch-types"}```

```
error: no matching package named `libpq` found
location searched: https://github.com/sanpii/libpq.rs?branch=arch-types
```

**Comment by petar-dambovaliev** [comment]
Nevermind, i am on an old version.
If i try to use this branch, i need to update the cargo edition and rustc, which requires other work.
Which i can't do right now.

**Comment by sanpii** [comment]
Ok, I had rebase the PR on 1.3.3 version, it’s a important fix I am going to backport it on old versions.

**Comment by petar-dambovaliev** [comment]
@sanpii i forked and checked out a 1.3.3 commit, applied the fixes and tested it on graviton. It works.

**Comment by sanpii** [comment]
Version 1.3.4, 1.4.1 and 2.0.1 published with this patch.
